// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consumer.proto

package models // import "github.com/w3y/go-connector/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RmqExchQueueInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AutoDelete           bool     `protobuf:"varint,3,opt,name=auto_delete,json=autoDelete,proto3" json:"auto_delete,omitempty"`
	Durable              bool     `protobuf:"varint,4,opt,name=durable,proto3" json:"durable,omitempty"`
	Internal             bool     `protobuf:"varint,5,opt,name=internal,proto3" json:"internal,omitempty"`
	Exclusive            bool     `protobuf:"varint,6,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	Nowait               bool     `protobuf:"varint,7,opt,name=nowait,proto3" json:"nowait,omitempty"`
	RoutingKey           string   `protobuf:"bytes,8,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	BatchAck             bool     `protobuf:"varint,9,opt,name=batch_ack,json=batchAck,proto3" json:"batch_ack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmqExchQueueInfo) Reset()         { *m = RmqExchQueueInfo{} }
func (m *RmqExchQueueInfo) String() string { return proto.CompactTextString(m) }
func (*RmqExchQueueInfo) ProtoMessage()    {}
func (*RmqExchQueueInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_consumer_a514f8b171b1c5dd, []int{0}
}
func (m *RmqExchQueueInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmqExchQueueInfo.Unmarshal(m, b)
}
func (m *RmqExchQueueInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmqExchQueueInfo.Marshal(b, m, deterministic)
}
func (dst *RmqExchQueueInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmqExchQueueInfo.Merge(dst, src)
}
func (m *RmqExchQueueInfo) XXX_Size() int {
	return xxx_messageInfo_RmqExchQueueInfo.Size(m)
}
func (m *RmqExchQueueInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RmqExchQueueInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RmqExchQueueInfo proto.InternalMessageInfo

func (m *RmqExchQueueInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RmqExchQueueInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RmqExchQueueInfo) GetAutoDelete() bool {
	if m != nil {
		return m.AutoDelete
	}
	return false
}

func (m *RmqExchQueueInfo) GetDurable() bool {
	if m != nil {
		return m.Durable
	}
	return false
}

func (m *RmqExchQueueInfo) GetInternal() bool {
	if m != nil {
		return m.Internal
	}
	return false
}

func (m *RmqExchQueueInfo) GetExclusive() bool {
	if m != nil {
		return m.Exclusive
	}
	return false
}

func (m *RmqExchQueueInfo) GetNowait() bool {
	if m != nil {
		return m.Nowait
	}
	return false
}

func (m *RmqExchQueueInfo) GetRoutingKey() string {
	if m != nil {
		return m.RoutingKey
	}
	return ""
}

func (m *RmqExchQueueInfo) GetBatchAck() bool {
	if m != nil {
		return m.BatchAck
	}
	return false
}

type ConsumerGroup struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumerGroup) Reset()         { *m = ConsumerGroup{} }
func (m *ConsumerGroup) String() string { return proto.CompactTextString(m) }
func (*ConsumerGroup) ProtoMessage()    {}
func (*ConsumerGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_consumer_a514f8b171b1c5dd, []int{1}
}
func (m *ConsumerGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerGroup.Unmarshal(m, b)
}
func (m *ConsumerGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerGroup.Marshal(b, m, deterministic)
}
func (dst *ConsumerGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerGroup.Merge(dst, src)
}
func (m *ConsumerGroup) XXX_Size() int {
	return xxx_messageInfo_ConsumerGroup.Size(m)
}
func (m *ConsumerGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerGroup proto.InternalMessageInfo

func (m *ConsumerGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RmqInputConf struct {
	Exch                 *RmqExchQueueInfo `protobuf:"bytes,1,opt,name=exch,proto3" json:"exch,omitempty"`
	Queue                *RmqExchQueueInfo `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	BatchAck             bool              `protobuf:"varint,3,opt,name=batch_ack,json=batchAck,proto3" json:"batch_ack,omitempty"`
	Mode                 string            `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RmqInputConf) Reset()         { *m = RmqInputConf{} }
func (m *RmqInputConf) String() string { return proto.CompactTextString(m) }
func (*RmqInputConf) ProtoMessage()    {}
func (*RmqInputConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_consumer_a514f8b171b1c5dd, []int{2}
}
func (m *RmqInputConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmqInputConf.Unmarshal(m, b)
}
func (m *RmqInputConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmqInputConf.Marshal(b, m, deterministic)
}
func (dst *RmqInputConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmqInputConf.Merge(dst, src)
}
func (m *RmqInputConf) XXX_Size() int {
	return xxx_messageInfo_RmqInputConf.Size(m)
}
func (m *RmqInputConf) XXX_DiscardUnknown() {
	xxx_messageInfo_RmqInputConf.DiscardUnknown(m)
}

var xxx_messageInfo_RmqInputConf proto.InternalMessageInfo

func (m *RmqInputConf) GetExch() *RmqExchQueueInfo {
	if m != nil {
		return m.Exch
	}
	return nil
}

func (m *RmqInputConf) GetQueue() *RmqExchQueueInfo {
	if m != nil {
		return m.Queue
	}
	return nil
}

func (m *RmqInputConf) GetBatchAck() bool {
	if m != nil {
		return m.BatchAck
	}
	return false
}

func (m *RmqInputConf) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

type RmqOutRoutingConf struct {
	RoutingKey           string   `protobuf:"bytes,1,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RmqOutRoutingConf) Reset()         { *m = RmqOutRoutingConf{} }
func (m *RmqOutRoutingConf) String() string { return proto.CompactTextString(m) }
func (*RmqOutRoutingConf) ProtoMessage()    {}
func (*RmqOutRoutingConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_consumer_a514f8b171b1c5dd, []int{3}
}
func (m *RmqOutRoutingConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmqOutRoutingConf.Unmarshal(m, b)
}
func (m *RmqOutRoutingConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmqOutRoutingConf.Marshal(b, m, deterministic)
}
func (dst *RmqOutRoutingConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmqOutRoutingConf.Merge(dst, src)
}
func (m *RmqOutRoutingConf) XXX_Size() int {
	return xxx_messageInfo_RmqOutRoutingConf.Size(m)
}
func (m *RmqOutRoutingConf) XXX_DiscardUnknown() {
	xxx_messageInfo_RmqOutRoutingConf.DiscardUnknown(m)
}

var xxx_messageInfo_RmqOutRoutingConf proto.InternalMessageInfo

func (m *RmqOutRoutingConf) GetRoutingKey() string {
	if m != nil {
		return m.RoutingKey
	}
	return ""
}

func (m *RmqOutRoutingConf) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type RmqOutputConf struct {
	Exch                 *RmqExchQueueInfo    `protobuf:"bytes,1,opt,name=exch,proto3" json:"exch,omitempty"`
	Outputdefs           []*RmqOutRoutingConf `protobuf:"bytes,2,rep,name=outputdefs,proto3" json:"outputdefs,omitempty"`
	Mode                 string               `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RmqOutputConf) Reset()         { *m = RmqOutputConf{} }
func (m *RmqOutputConf) String() string { return proto.CompactTextString(m) }
func (*RmqOutputConf) ProtoMessage()    {}
func (*RmqOutputConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_consumer_a514f8b171b1c5dd, []int{4}
}
func (m *RmqOutputConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmqOutputConf.Unmarshal(m, b)
}
func (m *RmqOutputConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmqOutputConf.Marshal(b, m, deterministic)
}
func (dst *RmqOutputConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmqOutputConf.Merge(dst, src)
}
func (m *RmqOutputConf) XXX_Size() int {
	return xxx_messageInfo_RmqOutputConf.Size(m)
}
func (m *RmqOutputConf) XXX_DiscardUnknown() {
	xxx_messageInfo_RmqOutputConf.DiscardUnknown(m)
}

var xxx_messageInfo_RmqOutputConf proto.InternalMessageInfo

func (m *RmqOutputConf) GetExch() *RmqExchQueueInfo {
	if m != nil {
		return m.Exch
	}
	return nil
}

func (m *RmqOutputConf) GetOutputdefs() []*RmqOutRoutingConf {
	if m != nil {
		return m.Outputdefs
	}
	return nil
}

func (m *RmqOutputConf) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

type RmqTaskConf struct {
	Type                 string           `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Group                *ConsumerGroup   `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Inputs               []*RmqInputConf  `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*RmqOutputConf `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	DmsClients           []string         `protobuf:"bytes,6,rep,name=dms_clients,json=dmsClients,proto3" json:"dms_clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RmqTaskConf) Reset()         { *m = RmqTaskConf{} }
func (m *RmqTaskConf) String() string { return proto.CompactTextString(m) }
func (*RmqTaskConf) ProtoMessage()    {}
func (*RmqTaskConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_consumer_a514f8b171b1c5dd, []int{5}
}
func (m *RmqTaskConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RmqTaskConf.Unmarshal(m, b)
}
func (m *RmqTaskConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RmqTaskConf.Marshal(b, m, deterministic)
}
func (dst *RmqTaskConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RmqTaskConf.Merge(dst, src)
}
func (m *RmqTaskConf) XXX_Size() int {
	return xxx_messageInfo_RmqTaskConf.Size(m)
}
func (m *RmqTaskConf) XXX_DiscardUnknown() {
	xxx_messageInfo_RmqTaskConf.DiscardUnknown(m)
}

var xxx_messageInfo_RmqTaskConf proto.InternalMessageInfo

func (m *RmqTaskConf) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RmqTaskConf) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RmqTaskConf) GetGroup() *ConsumerGroup {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *RmqTaskConf) GetInputs() []*RmqInputConf {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *RmqTaskConf) GetOutputs() []*RmqOutputConf {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *RmqTaskConf) GetDmsClients() []string {
	if m != nil {
		return m.DmsClients
	}
	return nil
}

func init() {
	proto.RegisterType((*RmqExchQueueInfo)(nil), "pb.RmqExchQueueInfo")
	proto.RegisterType((*ConsumerGroup)(nil), "pb.ConsumerGroup")
	proto.RegisterType((*RmqInputConf)(nil), "pb.RmqInputConf")
	proto.RegisterType((*RmqOutRoutingConf)(nil), "pb.RmqOutRoutingConf")
	proto.RegisterType((*RmqOutputConf)(nil), "pb.RmqOutputConf")
	proto.RegisterType((*RmqTaskConf)(nil), "pb.RmqTaskConf")
}

func init() { proto.RegisterFile("proto/consumer.proto", fileDescriptor_consumer_a514f8b171b1c5dd) }

var fileDescriptor_consumer_a514f8b171b1c5dd = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x95, 0xfe, 0xdb, 0x76, 0xca, 0x4a, 0x5b, 0x6b, 0x41, 0x16, 0x20, 0x51, 0x15, 0xa1,
	0xad, 0x40, 0xb4, 0x52, 0x57, 0x9c, 0x38, 0x41, 0x41, 0xb0, 0xe2, 0x80, 0xb0, 0x38, 0x71, 0xa9,
	0x12, 0xc7, 0x6d, 0xa3, 0xc6, 0x76, 0x12, 0xdb, 0x6c, 0x7b, 0x87, 0x47, 0xe0, 0xd5, 0x78, 0x1e,
	0xe4, 0x49, 0xb2, 0xdb, 0x2e, 0xe5, 0xc0, 0xcd, 0xf3, 0xcd, 0xd7, 0xfa, 0x37, 0xdf, 0x38, 0x70,
	0x9e, 0x15, 0xda, 0xea, 0x29, 0xd7, 0xca, 0x38, 0x29, 0x8a, 0x09, 0x96, 0xa4, 0x91, 0x45, 0xa3,
	0x9f, 0x0d, 0x38, 0x63, 0x32, 0x7f, 0xbf, 0xe5, 0xeb, 0x2f, 0x4e, 0x38, 0x71, 0xa5, 0x96, 0x9a,
	0x10, 0x68, 0xa9, 0x50, 0x0a, 0x1a, 0x0c, 0x83, 0x71, 0x8f, 0xe1, 0xd9, 0x6b, 0x76, 0x97, 0x09,
	0xda, 0x28, 0x35, 0x7f, 0x26, 0x4f, 0xa0, 0x1f, 0x3a, 0xab, 0x17, 0xb1, 0x48, 0x85, 0x15, 0xb4,
	0x39, 0x0c, 0xc6, 0x5d, 0x06, 0x5e, 0x7a, 0x87, 0x0a, 0xa1, 0x70, 0x12, 0xbb, 0x22, 0x8c, 0x52,
	0x41, 0x5b, 0xd8, 0xac, 0x4b, 0xf2, 0x10, 0xba, 0x89, 0xb2, 0xa2, 0x50, 0x61, 0x4a, 0xdb, 0xd8,
	0xba, 0xa9, 0xc9, 0x63, 0xe8, 0x89, 0x2d, 0x4f, 0x9d, 0x49, 0xbe, 0x0b, 0xda, 0xc1, 0xe6, 0xad,
	0x40, 0x1e, 0x40, 0x47, 0xe9, 0xeb, 0x30, 0xb1, 0xf4, 0x04, 0x5b, 0x55, 0xe5, 0x61, 0x0a, 0xed,
	0x6c, 0xa2, 0x56, 0x8b, 0x8d, 0xd8, 0xd1, 0x2e, 0x72, 0x42, 0x25, 0x7d, 0x12, 0x3b, 0xf2, 0x08,
	0x7a, 0x51, 0x68, 0xf9, 0x7a, 0x11, 0xf2, 0x0d, 0xed, 0x95, 0x77, 0xa2, 0xf0, 0x86, 0x6f, 0x46,
	0x4f, 0xe1, 0x74, 0x5e, 0xa5, 0xf3, 0xa1, 0xd0, 0x2e, 0x3b, 0x96, 0xc1, 0xe8, 0x57, 0x00, 0xf7,
	0x98, 0xcc, 0xaf, 0x54, 0xe6, 0xec, 0x5c, 0xab, 0x25, 0x19, 0x43, 0x4b, 0x6c, 0xf9, 0x1a, 0x4d,
	0xfd, 0xd9, 0xf9, 0x24, 0x8b, 0x26, 0x77, 0xc3, 0x64, 0xe8, 0x20, 0xcf, 0xa1, 0x9d, 0x7b, 0x09,
	0xf3, 0xfb, 0x97, 0xb5, 0xb4, 0x1c, 0x82, 0x36, 0x0f, 0x41, 0x3d, 0x97, 0xd4, 0x71, 0x99, 0x67,
	0x8f, 0xe1, 0x79, 0xf4, 0x11, 0x06, 0x4c, 0xe6, 0x9f, 0x9d, 0x65, 0xe5, 0xb4, 0xc8, 0x76, 0x27,
	0x8f, 0xe0, 0xaf, 0x3c, 0x8e, 0x6c, 0x74, 0xf4, 0x23, 0x80, 0xd3, 0xf2, 0xaf, 0xfe, 0x7f, 0xc4,
	0x57, 0x00, 0x1a, 0x7f, 0x17, 0x8b, 0xa5, 0xa1, 0x8d, 0x61, 0x73, 0xdc, 0x9f, 0xdd, 0xaf, 0xfc,
	0x87, 0x6c, 0x6c, 0xcf, 0x78, 0x74, 0xa0, 0xdf, 0x01, 0xf4, 0x99, 0xcc, 0xbf, 0x86, 0x66, 0x83,
	0x10, 0x35, 0x6a, 0xb0, 0xf7, 0xf8, 0xea, 0x05, 0x35, 0xf6, 0x1e, 0xe9, 0x05, 0xb4, 0x57, 0x7e,
	0x7b, 0x98, 0x5a, 0x7f, 0x36, 0xf0, 0xb7, 0x1f, 0xac, 0x95, 0x95, 0x7d, 0x32, 0x86, 0x4e, 0xe2,
	0xb7, 0x68, 0x68, 0x0b, 0x39, 0xcf, 0x2a, 0xce, 0x9b, 0xd5, 0xb2, 0xaa, 0x4f, 0x5e, 0xc0, 0x49,
	0x09, 0x6b, 0x68, 0x1b, 0xad, 0x83, 0xdb, 0x91, 0x6a, 0x6f, 0xed, 0xf0, 0x99, 0xc7, 0xd2, 0x2c,
	0x78, 0x9a, 0x08, 0x65, 0x0d, 0xed, 0x0c, 0x9b, 0x3e, 0xf3, 0x58, 0x9a, 0x79, 0xa9, 0xbc, 0xbd,
	0xf8, 0xf6, 0x6c, 0x95, 0xd8, 0xb5, 0x8b, 0x26, 0x5c, 0xcb, 0xe9, 0xf5, 0xe5, 0x6e, 0xba, 0xd2,
	0x2f, 0xb9, 0x56, 0x4a, 0x70, 0xab, 0x8b, 0x69, 0x16, 0xbd, 0xf6, 0xf3, 0xa7, 0x26, 0xea, 0xe0,
	0x27, 0x7a, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xa0, 0x01, 0x97, 0xba, 0x03, 0x00, 0x00,
}
